dist: xenial
language: python
env:
  - PIP_CACHE_DIR=$HOME/.cache/pip PIPENV_CACHE_DIR=$HOME/.cache/pipenv
cache:
  directories:
    $HOME/.cache/pip
    $HOME/.cache/pipenv
before_script:
  - pip install pipenv
jobs:
  include:
    - stage: test
      python: 3.6
      script: make setup test examples
    - stage: test
      python: 3.7
      script: make setup test examples
    - stage: test
      python: 3.8
      script: make setup test examples
    - stage: test
      python: pypy3
      script: pypy -m pip install pipenv && make PIPENV='pypy -m pipenv' setup test examples
    - stage: bench_and_coverage
      python: 3.7
      script:
        - make setup coverage setup-bench bench docs
    - stage: gh-pages
      python: 3.7
      provider: pages
      local_dir: docs
      github_token: $TOKEN_FOR_TRAVIS
      skip_cleanup: true
      keep_history: true
      on:
        branch: master
      script:
        make setup docs
