dist: xenial
language: python
env:
  - PIP_CACHE_DIR=$HOME/.cache/pip PIPENV_CACHE_DIR=$HOME/.cache/pipenv
cache:
  directories:
    $HOME/.cache/pip
    $HOME/.cache/pipenv
before_script:
  - pip install pipenv
jobs:
  include:
    - stage: test
      python: 3.6
      script: make setup test examples
    - stage: test
      python: 3.7
      script: make setup test examples
    - stage: test
      python: 3.8
      script: make setup test examples
    - stage: test
      python: pypy3
      script: pypy -m pip install pipenv && make PIPENV='pypy -m pipenv' setup test examples
    - stage: bench_and_coverage
      python: 3.7
      script:
        - make setup coverage setup-bench bench
    - stage: gh-pages
      python: 3.7
      skip_cleanup: true
      script: |
        if [ -n "$GITHUB_TOKEN" ]; then
          cd "$TRAVIS_BUILD_DIR"
          make setup docs
          cd docs
          git init
          git checkout -b gh-pages
          git add .
          git -c user.name='travis' -c user.email='travis' commit -m init
          git push -f -q https://yukinarit:$GITHUB_TOKEN@github.com/yukinarit/pyserde-gh-pages gh-pages &>/dev/null
          cd "$TRAVIS_BUILD_DIR"
        fi
