dist: xenial
language: python
env:
  - PIP_CACHE_DIR=$HOME/.cache/pip PIPENV_CACHE_DIR=$HOME/.cache/pipenv
cache:
  directories:
    $HOME/.cache/pip
    $HOME/.cache/pipenv
before_script:
  - pip install pipenv
  - make setup
jobs:
  include:
    - stage: test
      python: 3.6
      script: make examples
    - stage: test
      python: 3.7
      script: make examples setup-bench bench
    - stage: test
      python: 3.8
      script: make examples
    - stage: coverage
      python: 3.7
      script:
        - make coverage
        - coveralls
