name: Build and deploy docs

on:
  push:
    branches:
      - main

jobs:
  build_docs:
    name: Build docs and deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install poetry
        run: pip install poetry
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: |
          poetry install
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          source $HOME/.cargo/env
          cargo install mdbook
      - name: Get PR number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: all
      - name: Set commit message
        run: |
          if [ -z "$PR" ]
          then
            echo "COMMIT_MESSAGE=:octocat: Update docs" >> $GITHUB_ENV
          else
            echo "COMMIT_MESSAGE=:octocat: Update docs for #$PR" >> $GITHUB_ENV
          fi
        env:
          PR: ${{ steps.findPr.outputs.pr }}
      - name: Build docs
        run: make docs
      - name: Deploy on gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          commit-message: ${{ env.COMMIT_MESSAGE }}
          clean: true
          git-config-name: github-actions
          git-config-email: github-actions@github.com
