name: Tests

on: [push, pull_request]

jobs:

  test:
    name: Python [${{ matrix.python-version }}] on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Restore pip cache
      # Caching on Windows is turned off due to inconsistent behaviour
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ matrix.os }}-${{ env.pythonLocation }}-${{ hashFiles('**/Pipfile') }}
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --skip-lock --system --dev
        pip list
        cd examples && pipenv install --skip-lock --system --dev
    - name: Run tests
      run: |
        pytest tests --doctest-modules serde -v
        cd examples && python runner.py

  check_coverage:
    name: Check coverage
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ubuntu-latest-${{ env.pythonLocation }}-${{ hashFiles('**/Pipfile') }}
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --skip-lock --system --dev
    - name: Check coverage
      run: pytest tests --doctest-modules serde -v --cov=serde --cov-report term --cov-report xml
    - name: Upload coverage report to codecov.io
      uses: codecov/codecov-action@v1

  run_benchmark:
    name: Run benchmark
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ubuntu-latest-${{ env.pythonLocation }}-${{ hashFiles('**/Pipfile') }}
    - name: Install dependencies
      run: |
        pip install pipenv
        cd bench && pipenv install --skip-lock --system
    - name: Run benchmark
      run: |
        python bench/bench.py
